"""
qa.py — QA system that reads annotated markdown and answers user questions.

Key behavior change from the old verifier:
    - Reads hsbc_annotated.md (generated by verifier.py) instead of plain hsbc.md
    - Parses VERIFY comment tags from each table block
    - For CORRECT tables: answer directly from the annotated markdown
    - For INCORRECT tables: skip direct answer, return page image(s) from PDF_REF

The annotated markdown format:
    <!-- VERIFY: CORRECT | confidence=0.94 -->
    <!-- PDF_REF: page=5, section="Section C: Fees and Charges" -->
    | Fee Type         | Amount      | ...
    ...

    <!-- VERIFY: INCORRECT | reason=cell_boundary_bleed | confidence=0.61 -->
    <!-- PDF_REF: page=3, section="Tips to save you time and effort" -->
    | Service | **HSBC Mobile Banking** | ...
    ...
"""

from __future__ import annotations

import os
import re
import json
from pathlib import Path
from dataclasses import dataclass, field
from dotenv import load_dotenv
from openai import AzureOpenAI

load_dotenv()

client = AzureOpenAI(
    azure_endpoint=os.getenv("AZURE_OPENAI_ENDPOINT"),
    api_key=os.getenv("AZURE_OPENAI_API_KEY"),
    api_version=os.getenv("AZURE_OPENAI_API_VERSION"),
)

# ── Paths ──────────────────────────────────────────────────────────────────────

BASE            = Path(__file__).parent
OUTPUT_DIR      = BASE / "hsbc_output"
ANNOTATED_PATH  = OUTPUT_DIR / "hsbc_annotated.md"   # NEW: annotated markdown
CONTEXT_PATH    = ANNOTATED_PATH                      # read annotated markdown
REPORT_PATH     = OUTPUT_DIR / "verification" / "annotated_report.json"
# FIX: Use the actual absolute path where page images are stored
PAGE_IMAGES_DIR = Path("/Users/goodtam8/Documents/Programming/QA-For-table-and-graph/hsbc_output/verification/page_images")


# ── Data structures ────────────────────────────────────────────────────────────

@dataclass
class AnnotatedTable:
    """A markdown table with its verification and PDF reference tags."""
    table_index: int
    label: str           # "CORRECT" | "INCORRECT" | "REVIEW" | "UNKNOWN"
    confidence: float
    error_reasons: list[str] = field(default_factory=list)
    pdf_page: int | None = None
    section: str | None = None
    raw_table: str = ""  # full markdown table text including tags
    md_table_body: str = ""  # just the table lines (no tags)


@dataclass
class QAAnswer:
    """Result returned by the QA system."""
    status: str          # "answered" | "flagged" | "partial"
    answer: str          # LLM answer text or refusal message
    images: list[str]    # absolute paths to relevant page images
    warning: str | None
    table_verdict: AnnotatedTable | None = None  # the table that was used

    def to_dict(self) -> dict:
        return {
            "status": self.status,
            "answer": self.answer,
            "images": [str(p) for p in self.images],
            "warning": self.warning,
            "table_label": self.table_verdict.label if self.table_verdict else None,
            "table_confidence": self.table_verdict.confidence if self.table_verdict else None,
        }


# ── Annotation tag parser ──────────────────────────────────────────────────────

def parse_annotated_tables(markdown: str) -> list[AnnotatedTable]:
    """
    Parse all VERIFY-tagged tables from annotated markdown.

    Handles both heuristic (verifier.py) and LLM-assisted annotation formats:
        <!-- VERIFY: CORRECT | confidence=0.94 -->
        <!-- VERIFY: INCORRECT | reason=cell_boundary_bleed | confidence=0.61 -->
        <!-- PDF_REF: page=5, section="Section C: Fees and Charges" -->
    """
    tables: list[AnnotatedTable] = []
    table_index = 0

    VERIFY_RE = re.compile(
        r"<!--\s*VERIFY:\s*(CORRECT|INCORRECT|REVIEW)\s*"
        r"(?:\|[^>]*?confidence=([\d.]+)[^>]*?)?"
        r"(?:\|[^>]*?reason=([^\s|>]+)[^>]*?)?"
        r"(?:\|[^>]*?reason=([^\s|>]+))?\s*-->",
        re.IGNORECASE,
    )
    PDF_REF_RE = re.compile(
        r'<!--\s*PDF_REF:\s*page=(\d+)(?:,\s*section="([^"]*)")?\s*-->',
        re.IGNORECASE,
    )

    lines = markdown.split("\n")
    in_table = False
    current_verify_tag: str | None = None
    current_pdf_ref_tag: str | None = None
    current_table_lines: list[str] = []
    blocks: list[tuple[str | None, str | None, list[str]]] = []

    for line in lines:
        stripped = line.strip()

        verify_m = VERIFY_RE.search(line)
        if verify_m:
            if current_table_lines:
                blocks.append((current_verify_tag, current_pdf_ref_tag, current_table_lines))
            current_verify_tag = verify_m.group(0)
            current_pdf_ref_tag = None
            current_table_lines = []
            in_table = False
            continue

        pdf_ref_m = PDF_REF_RE.search(line)
        if pdf_ref_m:
            current_pdf_ref_tag = pdf_ref_m.group(0)
            continue

        is_table = stripped.startswith("|") and stripped.endswith("|")
        is_delimiter = bool(re.match(r"^\|[\s\-:|]+\|\s*$", stripped))

        if is_table or is_delimiter:
            if not in_table:
                if current_table_lines:
                    blocks.append((current_verify_tag, current_pdf_ref_tag, current_table_lines))
                current_table_lines = []
                in_table = True
            current_table_lines.append(line)
        else:
            if in_table and current_table_lines:
                blocks.append((current_verify_tag, current_pdf_ref_tag, current_table_lines))
                current_verify_tag = None
                current_pdf_ref_tag = None
                current_table_lines = []
            in_table = False
            current_table_lines = []

    if current_table_lines:
        blocks.append((current_verify_tag, current_pdf_ref_tag, current_table_lines))

    for verify_tag, pdf_ref_tag, table_lines in blocks:
        if not table_lines:
            continue

        label = "UNKNOWN"
        confidence = 0.0
        error_reasons: list[str] = []

        if verify_tag:
            vm = VERIFY_RE.search(verify_tag)
            if vm:
                label = vm.group(1).upper()
                conf_str = vm.group(2)
                if conf_str:
                    confidence = float(conf_str)
                reasons = [r for r in [vm.group(3), vm.group(4)] if r]
                error_reasons = reasons

        pdf_page: int | None = None
        section: str | None = None
        if pdf_ref_tag:
            pm = PDF_REF_RE.search(pdf_ref_tag)
            if pm:
                pdf_page = int(pm.group(1))
                section = pm.group(2)

        raw = "\n".join(table_lines)
        md_body = "\n".join(table_lines)

        tables.append(AnnotatedTable(
            table_index=table_index,
            label=label,
            confidence=confidence,
            error_reasons=error_reasons,
            pdf_page=pdf_page,
            section=section,
            raw_table=raw,
            md_table_body=md_body,
        ))
        table_index += 1

    return tables


# ── Loaders ───────────────────────────────────────────────────────────────────

def load_annotated_markdown() -> tuple[str, list[AnnotatedTable]]:
    """Load the annotated markdown and parse its table tags."""
    if not ANNOTATED_PATH.exists():
        plain = BASE / "hsbc.md"
        if plain.exists():
            text = plain.read_text(encoding="utf-8")
            tables = []
            for i, tbl in enumerate(_extract_tables_from_markdown(text)):
                tables.append(AnnotatedTable(
                    table_index=i,
                    label="UNKNOWN",
                    confidence=0.0,
                    error_reasons=["No annotation available"],
                    pdf_page=None,
                    section=None,
                    raw_table=tbl,
                    md_table_body=tbl,
                ))
            return text, tables
        return "", []

    text = ANNOTATED_PATH.read_text(encoding="utf-8")
    tables = parse_annotated_tables(text)
    return text, tables


def _extract_tables_from_markdown(markdown: str) -> list[str]:
    """Extract raw GFM table blocks from plain markdown."""
    lines = markdown.split("\n")
    tables: list[str] = []
    in_table = False
    current: list[str] = []

    for line in lines:
        stripped = line.strip()
        is_table = stripped.startswith("|") and stripped.endswith("|")
        is_delimiter = bool(re.match(r"^\|[\s\-:|]+\|\s*$", stripped))

        if is_table or is_delimiter:
            if not in_table:
                in_table = True
            current.append(line)
        else:
            if in_table and current:
                tables.append("\n".join(current))
                current = []
            in_table = False

    if current:
        tables.append("\n".join(current))

    return tables


# ── Page image lookup ──────────────────────────────────────────────────────────

def find_page_images(pages: list[int]) -> list[Path]:
    """
    Return Path objects for page image files matching the given page numbers.

    FIX: Always uses the absolute PAGE_IMAGES_DIR path, then also tries
    the project-relative path as a fallback. Supports naming conventions:
    page_001.png, page_002.jpg, page_1.png, etc.
    """
    results: list[Path] = []

    # Candidate directories: absolute path first, then relative fallback
    candidate_dirs: list[Path] = [PAGE_IMAGES_DIR]
    relative_dir = OUTPUT_DIR / "verification" / "page_images"
    if relative_dir != PAGE_IMAGES_DIR and relative_dir.exists():
        candidate_dirs.append(relative_dir)

    for search_dir in candidate_dirs:
        if not search_dir.exists():
            continue

        images: list[Path] = []
        for page in pages:
            found = False
            for pattern in [
                f"page_{page:03d}.png",
                f"page_{page:03d}.jpg",
                f"page_{page:03d}.jpeg",
                f"page_{page}.png",
                f"page_{page}.jpg",
                f"page_{page}.jpeg",
            ]:
                p = search_dir / pattern
                if p.exists():
                    images.append(p)
                    found = True
                    break

            if not found:
                # Glob fallback: any file containing the page number
                globs = list(search_dir.glob(f"*page*{page}*"))
                if not globs:
                    # Try zero-padded glob
                    globs = list(search_dir.glob(f"*{page:03d}*"))
                if globs:
                    images.append(sorted(globs)[0])

        if images:
            results = images
            break  # Found images in this directory, stop searching

    # Deduplicate while preserving order
    seen: set[Path] = set()
    unique: list[Path] = []
    for img in results:
        if img not in seen:
            seen.add(img)
            unique.append(img)
    return unique


def list_available_page_images() -> list[Path]:
    """
    List all page images available in PAGE_IMAGES_DIR.
    Useful for debugging when a specific page is not found.
    """
    if not PAGE_IMAGES_DIR.exists():
        return []
    exts = {".png", ".jpg", ".jpeg"}
    return sorted(p for p in PAGE_IMAGES_DIR.iterdir() if p.suffix.lower() in exts)


# ── LLM answer ────────────────────────────────────────────────────────────────

def answerdirectly(question: str, context: str) -> str:
    """
    Use the LLM to answer a question using the provided context (annotated markdown).
    """
    response = client.chat.completions.create(
        model=os.getenv("AZURE_OPENAI_DEPLOYMENT_NAME"),
        messages=[
            {
                "role": "system",
                "content": (
                    "You are a helpful QA assistant for bank tariff documents. "
                    "Answer the user's question using only the provided document content. "
                    "If the answer is not in the document, say that you cannot find it. "
                    "Be precise with fee amounts, account types, and conditions."
                ),
            },
            {
                "role": "user",
                "content": (
                    f"Here is the document:\n\n```markdown\n{context}\n```\n\n"
                    f"User question:\n{question}"
                ),
            },
        ],
        temperature=0,
    )
    return response.choices[0].message.content


# ── Table relevance scoring ─────────────────────────────────────────────────────

def score_table_relevance(question: str, table: AnnotatedTable, full_markdown: str) -> float:
    """
    Score how relevant a table is to a user question (0.0 = irrelevant, 1.0 = highly relevant).
    """
    q_lower = question.lower()
    q_keywords = set(re.findall(r"[a-z]{3,}", q_lower))

    score = 0.0

    if table.section:
        sec_lower = table.section.lower()
        if any(kw in sec_lower for kw in q_keywords):
            score += 0.5

    page_hint = re.search(r"\b(?:page|p\.?)\s*(\d+)\b", q_lower)
    if page_hint and table.pdf_page:
        if int(page_hint.group(1)) == table.pdf_page:
            score += 0.6

    body_lower = table.md_table_body.lower()
    for kw in q_keywords:
        if kw in body_lower:
            score += 0.1

    return min(score, 1.0)


def find_relevant_tables(question: str, tables: list[AnnotatedTable], full_markdown: str) -> list[AnnotatedTable]:
    """Return tables relevant to the question, sorted by relevance score descending."""
    scored = [
        (score_table_relevance(question, tbl, full_markdown), tbl)
        for tbl in tables
    ]
    scored.sort(key=lambda x: x[0], reverse=True)
    return [tbl for score, tbl in scored if score > 0]


# ── Main QA logic ─────────────────────────────────────────────────────────────

def answer(question: str) -> QAAnswer:
    """
    Answer a question about the HSBC document using annotated markdown.

    Strategy:
      1. Load annotated markdown + parse VERIFY tags
      2. Find tables relevant to the question
      3. Check each table's VERIFY label:
         - CORRECT  → answer directly from the annotated table content
         - REVIEW   → answer directly but add a warning
         - INCORRECT / UNKNOWN → return page images from PDF_REF page numbers
      4. If no relevant table found → answer directly from full annotated markdown

    Returns QAAnswer with:
        status  : "answered" | "flagged" | "partial"
        answer  : str (LLM answer or refusal)
        images  : list of page image paths
        warning : str | None
    """
    # ── 1. Load annotated markdown ─────────────────────────────────────────
    full_markdown, annotated_tables = load_annotated_markdown()

    if not full_markdown.strip():
        return QAAnswer(
            status="flagged",
            answer="No annotated document found. Please run the verifier first.",
            images=[],
            warning="⚠️ No annotated markdown available. Run: python verifier.py",
        )

    # ── 2. Find relevant tables ────────────────────────────────────────────
    relevant = find_relevant_tables(question, annotated_tables, full_markdown)

    if relevant:
        table = relevant[0]

        # ── 3a. CORRECT → answer directly ─────────────────────────────────
        if table.label == "CORRECT":
            llm_answer = answerdirectly(question, table.md_table_body)
            return QAAnswer(
                status="answered",
                answer=llm_answer,
                images=[],
                warning=None,
                table_verdict=table,
            )

        # ── 3b. REVIEW → answer with warning ──────────────────────────────
        if table.label == "REVIEW":
            reason_str = ", ".join(table.error_reasons) if table.error_reasons else "uncertain_verification"
            warning = (
                f"⚠️  This table has REVIEW status (confidence={table.confidence:.2f}). "
                f"Reason: {reason_str}. "
                f"Answer is provided but may need verification."
            )
            llm_answer = answerdirectly(question, table.md_table_body)
            return QAAnswer(
                status="answered",
                answer=llm_answer,
                images=[],
                warning=warning,
                table_verdict=table,
            )

        # ── 3c. INCORRECT / UNKNOWN → return page images ──────────────────
        page_images: list[Path] = []
        if table.pdf_page is not None:
            page_images = find_page_images([table.pdf_page])

        # FIX: If no image found via pdf_page, warn the user with diagnostics
        image_debug = ""
        if not page_images:
            available = list_available_page_images()
            if available:
                available_str = ", ".join(p.name for p in available[:10])
                image_debug = (
                    f" (Note: No image found for page {table.pdf_page}. "
                    f"Available images: {available_str})"
                )
            else:
                image_debug = (
                    f" (Note: Page images directory is empty or not found at: {PAGE_IMAGES_DIR})"
                )

        reason_str = ", ".join(table.error_reasons) if table.error_reasons else "verification_failed"
        warning = (
            f"⚠️  The relevant table was verified as {table.label} "
            f"(confidence={table.confidence:.2f}). "
            f"Reason: {reason_str}. "
            f"The answer cannot be provided from the markdown as it may contain errors. "
            f"Please consult the original page image(s) below.{image_debug}"
        )

        return QAAnswer(
            status="flagged",
            answer=(
                f"I cannot provide a reliable answer for this question because the relevant "
                f"section was verified as {table.label} "
                f"(reason: {reason_str}, confidence={table.confidence:.2f}). "
                f"Please refer to the original page image(s) for the accurate information."
            ),
            images=page_images,
            warning=warning,
            table_verdict=table,
        )

    # ── 4. No relevant table found → answer from full markdown ──────────────
    llm_answer = answerdirectly(question, full_markdown)
    return QAAnswer(
        status="answered",
        answer=llm_answer,
        images=[],
        warning=None,
    )


# ── CLI helper ────────────────────────────────────────────────────────────────

def _print_result(result: QAAnswer) -> None:
    """Pretty-print a QAAnswer result to stdout."""
    print()
    if result.warning:
        print(result.warning)
        print()
    print("Answer:", result.answer)
    if result.images:
        print()
        print("Relevant page image(s) (verified INCORRECT — consult for accuracy):")
        for img in result.images:
            print(f"  {img}")
        print()
    elif result.status == "flagged":
        # FIX: Tell user explicitly that no images were found instead of silent failure
        print()
        print("⚠️  No page images were found to display.")
        print(f"  Expected image directory: {PAGE_IMAGES_DIR}")
        if PAGE_IMAGES_DIR.exists():
            all_imgs = list_available_page_images()
            if all_imgs:
                print(f"  Available images ({len(all_imgs)} total):")
                for img in all_imgs[:5]:
                    print(f"    {img.name}")
                if len(all_imgs) > 5:
                    print(f"    ... and {len(all_imgs) - 5} more")
            else:
                print("  Directory exists but contains no image files.")
        else:
            print("  Directory does not exist. Run the parser/verifier pipeline first.")
        print()
    if result.table_verdict:
        print(f"[Table {result.table_verdict.table_index + 1}] "
              f"Label: {result.table_verdict.label} | "
              f"Confidence: {result.table_verdict.confidence:.2f} | "
              f"Page: {result.table_verdict.pdf_page or 'N/A'}")
    print()


# ── Entry point ────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    q = input("Ask a question about the HSBC document: ")
    result = answer(q)
    _print_result(result)
