"""
qa.py — QA system that reads annotated markdown and answers user questions.

Key behavior change from the old verifier:
    - Reads hsbc_annotated.md (generated by verifier.py) instead of plain hsbc.md
    - Parses VERIFY comment tags from each table block
    - For CORRECT tables: answer directly from the annotated markdown
    - For INCORRECT tables: skip direct answer, return page image(s) from PDF_REF

The annotated markdown format:
    <!-- VERIFY: CORRECT | confidence=0.94 -->
    <!-- PDF_REF: page=5, section="Section C: Fees and Charges" -->
    | Fee Type         | Amount      | ...
    ...

    <!-- VERIFY: INCORRECT | reason=cell_boundary_bleed | confidence=0.61 -->
    <!-- PDF_REF: page=3, section="Tips to save you time and effort" -->
    | Service | **HSBC Mobile Banking** | ...
    ...
"""

from __future__ import annotations

import math
import os
import re
import json
from pathlib import Path
from dataclasses import dataclass, field
from dotenv import load_dotenv
from openai import AzureOpenAI

load_dotenv()

client = AzureOpenAI(
    azure_endpoint=os.getenv("AZURE_OPENAI_ENDPOINT"),
    api_key=os.getenv("AZURE_OPENAI_API_KEY"),
    api_version=os.getenv("AZURE_OPENAI_API_VERSION"),
)

_EMBEDDING_MODEL = os.getenv("AZURE_OPENAI_EMBEDDING_DEPLOYMENT", "text-embedding-3-small")
_embedding_cache: dict[int, list[float]] = {}
_embedding_ready = False
_table_indices: list[int] = []

# ── Paths ──────────────────────────────────────────────────────────────────────

BASE            = Path(__file__).parent
OUTPUT_DIR      = BASE / "hsbc_output"
ANNOTATED_PATH  = OUTPUT_DIR / "hsbc_annotated.md"   # NEW: annotated markdown
CONTEXT_PATH    = ANNOTATED_PATH                      # read annotated markdown
REPORT_PATH     = OUTPUT_DIR / "verification" / "annotated_report.json"
PAGE_IMAGES_DIR = OUTPUT_DIR / "verification" / "page_images"


# ── Data structures ────────────────────────────────────────────────────────────

@dataclass
class AnnotatedTable:
    """A markdown table with its verification and PDF reference tags."""
    table_index: int
    label: str           # "CORRECT" | "INCORRECT" | "REVIEW" | "UNKNOWN"
    confidence: float
    error_reasons: list[str] = field(default_factory=list)
    pdf_page: int | None = None
    section: str | None = None
    raw_table: str = ""  # full markdown table text including tags
    md_table_body: str = ""  # just the table lines (no tags)


@dataclass
class QAAnswer:
    """Result returned by the QA system."""
    status: str          # "answered" | "flagged" | "partial"
    answer: str          # LLM answer text or refusal message
    images: list[str]    # absolute paths to relevant page images
    warning: str | None
    table_verdict: AnnotatedTable | None = None  # the table that was used

    def to_dict(self) -> dict:
        return {
            "status": self.status,
            "answer": self.answer,
            "images": [str(p) for p in self.images],
            "warning": self.warning,
            "table_label": self.table_verdict.label if self.table_verdict else None,
            "table_confidence": self.table_verdict.confidence if self.table_verdict else None,
        }


# ── Annotation tag parser ──────────────────────────────────────────────────────

def parse_annotated_tables(markdown: str) -> list[AnnotatedTable]:
    """
    Parse all VERIFY-tagged tables from annotated markdown.

    Handles both heuristic (verifier.py) and LLM-assisted annotation formats:
        <!-- VERIFY: CORRECT | confidence=0.94 -->
        <!-- VERIFY: INCORRECT | reason=cell_boundary_bleed | confidence=0.61 -->
        <!-- PDF_REF: page=5, section="Section C: Fees and Charges" -->
    """
    tables: list[AnnotatedTable] = []
    table_index = 0

    # Pattern to match a block: tags followed by a GFM table
    # Matches from the first VERIFY tag through the table
    BLOCK_RE = re.compile(
        r"""
        (?P<tags>
            <!--\s*VERIFY:\s*(?P<label>CORRECT|INCORRECT|REVIEW)\s*
            (?:
                \|\s*reason=(?P<reasons>[^|\s]+(?:\s+[^|\s]+)*)
                |
                \|\s*confidence=(?P<confidence>[\d.]+)
            )*\s*-->
            \s*
            <!--\s*PDF_REF:\s*
            (?P<pdf_ref>[^>]*?)
            -->\s*
        )?
        (?P<table>
            \|[^\n]*\|[\r\n]+
            (?:\|[\s\-:|]+\|[\r\n]+)?
            (?:\|[^\n]*\|[\r\n]*)*
        )
        """,
        re.VERBOSE | re.MULTILINE,
    )

    # Simple fallback: just find all VERIFY tags and their following tables
    VERIFY_RE = re.compile(
        r"<!--\s*VERIFY:\s*(CORRECT|INCORRECT|REVIEW)\s*"
        r"(?:\|[^>]*?confidence=([\d.]+)[^>]*?)?"
        r"(?:\|[^>]*?reason=([^\s|>]+)[^>]*?)?"
        r"(?:\|[^>]*?reason=([^\s|>]+))?\s*-->",
        re.IGNORECASE,
    )
    PDF_REF_RE = re.compile(
        r'<!--\s*PDF_REF:\s*page=(\d+)(?:,\s*section="([^"]*)")?\s*-->',
        re.IGNORECASE,
    )

    # Split by tables
    TABLE_SPLIT_RE = re.compile(
        r"(?=^\|[\s\S]*?\|[\r\n]+)",
        re.MULTILINE,
    )

    # Split the markdown into potential table blocks
    lines = markdown.split("\n")
    in_table = False
    current_block_lines: list[str] = []
    current_verify_tag: str | None = None
    current_pdf_ref_tag: str | None = None
    current_table_lines: list[str] = []
    blocks: list[tuple[str | None, str | None, list[str]]] = []

    for line in lines:
        stripped = line.strip()

        # Check for VERIFY tag
        verify_m = VERIFY_RE.search(line)
        if verify_m:
            # Flush previous block
            if current_table_lines:
                blocks.append((current_verify_tag, current_pdf_ref_tag, current_table_lines))
            current_verify_tag = verify_m.group(0)
            current_pdf_ref_tag = None
            current_table_lines = []
            in_table = False
            continue

        # Check for PDF_REF tag
        pdf_ref_m = PDF_REF_RE.search(line)
        if pdf_ref_m:
            current_pdf_ref_tag = pdf_ref_m.group(0)
            continue

        # Check if this is a table row
        is_table = stripped.startswith("|") and stripped.endswith("|")
        is_delimiter = bool(re.match(r"^\|[\s\-:|]+\|\s*$", stripped))

        if is_table or is_delimiter:
            if not in_table:
                # Flush previous non-table block
                if current_table_lines:
                    blocks.append((current_verify_tag, current_pdf_ref_tag, current_table_lines))
                current_verify_tag = current_verify_tag
                current_pdf_ref_tag = current_pdf_ref_tag
                current_table_lines = []
                in_table = True
            current_table_lines.append(line)
        else:
            if in_table and current_table_lines:
                blocks.append((current_verify_tag, current_pdf_ref_tag, current_table_lines))
                current_verify_tag = None
                current_pdf_ref_tag = None
                current_table_lines = []
            in_table = False
            current_table_lines = []

    # Flush last block
    if current_table_lines:
        blocks.append((current_verify_tag, current_pdf_ref_tag, current_table_lines))

    # Parse each block
    for verify_tag, pdf_ref_tag, table_lines in blocks:
        if not table_lines:
            continue

        label = "UNKNOWN"
        confidence = 0.0
        error_reasons: list[str] = []

        if verify_tag:
            vm = VERIFY_RE.search(verify_tag)
            if vm:
                label = vm.group(1).upper()
                conf_str = vm.group(2)
                if conf_str:
                    confidence = float(conf_str)
                reasons = [r for r in [vm.group(3), vm.group(4)] if r]
                error_reasons = reasons

        pdf_page: int | None = None
        section: str | None = None
        if pdf_ref_tag:
            pm = PDF_REF_RE.search(pdf_ref_tag)
            if pm:
                pdf_page = int(pm.group(1))
                section = pm.group(2)

        raw = "\n".join(table_lines)
        md_body = "\n".join(table_lines)

        tables.append(AnnotatedTable(
            table_index=table_index,
            label=label,
            confidence=confidence,
            error_reasons=error_reasons,
            pdf_page=pdf_page,
            section=section,
            raw_table=raw,
            md_table_body=md_body,
        ))
        table_index += 1

    return tables


# ── Loaders ───────────────────────────────────────────────────────────────────

def load_annotated_markdown() -> tuple[str, list[AnnotatedTable]]:
    """Load the annotated markdown and parse its table tags."""
    if not ANNOTATED_PATH.exists():
        # Fall back to plain markdown if annotated version doesn't exist
        plain = BASE / "hsbc.md"
        if plain.exists():
            text = plain.read_text(encoding="utf-8")
            tables = []
            # No tags → all tables treated as UNKNOWN (flagged for safety)
            for i, tbl in enumerate(_extract_tables_from_markdown(text)):
                tables.append(AnnotatedTable(
                    table_index=i,
                    label="UNKNOWN",
                    confidence=0.0,
                    error_reasons=["No annotation available"],
                    pdf_page=None,
                    section=None,
                    raw_table=tbl,
                    md_table_body=tbl,
                ))
            return text, tables
        return "", []

    text = ANNOTATED_PATH.read_text(encoding="utf-8")
    tables = parse_annotated_tables(text)
    return text, tables


def _extract_tables_from_markdown(markdown: str) -> list[str]:
    """Extract raw GFM table blocks from plain markdown."""
    lines = markdown.split("\n")
    tables: list[str] = []
    in_table = False
    current: list[str] = []

    for line in lines:
        stripped = line.strip()
        is_table = stripped.startswith("|") and stripped.endswith("|")
        is_delimiter = bool(re.match(r"^\|[\s\-:|]+\|\s*$", stripped))

        if is_table or is_delimiter:
            if not in_table:
                in_table = True
            current.append(line)
        else:
            if in_table and current:
                tables.append("\n".join(current))
                current = []
            in_table = False

    if current:
        tables.append("\n".join(current))

    return tables


# ── Page image lookup ──────────────────────────────────────────────────────────

def find_page_images(pages: list[int]) -> list[Path]:
    """
    Return Path objects for page image files matching the given page numbers.
    Supports naming conventions: page_001.png, page_002.jpg, etc.
    """
    if not PAGE_IMAGES_DIR.exists():
        return []

    images: list[Path] = []
    for page in pages:
        for pattern in [
            f"page_{page:03d}.png",
            f"page_{page:03d}.jpg",
            f"page_{page}.png",
            f"page_{page}.jpg",
        ]:
            p = PAGE_IMAGES_DIR / pattern
            if p.exists():
                images.append(p)
                break
        else:
            globs = list(PAGE_IMAGES_DIR.glob(f"*page*{page}*"))
            if globs:
                images.append(sorted(globs)[0])

    # Deduplicate
    seen: set[Path] = set()
    unique: list[Path] = []
    for img in images:
        if img not in seen:
            seen.add(img)
            unique.append(img)
    return unique


# ── LLM answer ────────────────────────────────────────────────────────────────

def answerdirectly(question: str, context: str) -> str:
    """
    Use the LLM to answer a question using the provided context (annotated markdown).
    """
    response = client.chat.completions.create(
        model=os.getenv("AZURE_OPENAI_DEPLOYMENT_NAME"),
        messages=[
            {
                "role": "system",
                "content": (
                    "You are a helpful QA assistant for bank tariff documents. "
                    "Answer the user's question using only the provided document content. "
                    "If the answer is not in the document, say that you cannot find it. "
                    "Be precise with fee amounts, account types, and conditions."
                ),
            },
            {
                "role": "user",
                "content": (
                    f"Here is the document:\n\n```markdown\n{context}\n```\n\n"
                    f"User question:\n{question}"
                ),
            },
        ],
        temperature=0,
    )
    return response.choices[0].message.content


# ── Table relevance scoring ─────────────────────────────────────────────────────

def embed(text: str) -> list[float]:
    """
    Return an embedding vector for the provided text.
    """
    response = client.embeddings.create(
        model=_EMBEDDING_MODEL,
        input=text,
    )
    return response.data[0].embedding


def cosine_similarity(a: list[float], b: list[float]) -> float:
    """
    Compute cosine similarity between two embedding vectors.
    """
    if not a or not b:
        return 0.0

    dot = 0.0
    norm_a = 0.0
    norm_b = 0.0
    for x, y in zip(a, b):
        dot += x * y
        norm_a += x * x
        norm_b += y * y
    denom = math.sqrt(norm_a) * math.sqrt(norm_b)
    if denom == 0:
        return 0.0
    return dot / denom


def _ensure_table_embeddings(tables: list[AnnotatedTable]) -> None:
    """
    Populate module-level embedding cache for every annotated table,
    embedding each table only once per session.
    """
    global _embedding_ready, _table_indices

    if _embedding_ready and all(idx in _embedding_cache for idx in _table_indices):
        return

    _table_indices = [table.table_index for table in tables]
    for table in tables:
        if table.table_index not in _embedding_cache:
            # Extract meaningful row content from the markdown table body
            body_lines = table.md_table_body.splitlines()
            # Skip header and separator rows, include actual data rows
            content_lines = [line for line in body_lines if line.strip() and not re.match(r'^\|[\s\-:|]+\|\s*$', line.strip())]
            # Take first 10 content rows to capture topics without too much noise
            sample_content = '\n'.join(content_lines[:10]) if content_lines else table.md_table_body
            text = f"{table.section or ''}\n{sample_content}"
            _embedding_cache[table.table_index] = embed(text)

    _embedding_ready = True


def _select_candidate_indices(question: str, tables: list[AnnotatedTable], top_k: int = 5, threshold: float = 0.0) -> list[int]:
    """
    Select candidate table indices using embedding similarity.
    """
    if not tables:
        return []

    _ensure_table_embeddings(tables)
    question_embedding = embed(question)

    ranked = []
    for table in tables:
        cached = _embedding_cache.get(table.table_index)
        if cached is None:
            continue
        score = cosine_similarity(question_embedding, cached)
        ranked.append((score, table.table_index))

    ranked.sort(key=lambda item: item[0], reverse=True)
    return [index for score, index in ranked if score > threshold][:top_k]


def _rerank_with_llm(question: str, tables: list[AnnotatedTable], candidate_indices: list[int]) -> list[int]:
    """
    Ask the LLM to re-rank candidate table indices using compact summaries.

    candidate_indices: list of table_index values (not list positions).
    Returns a re-ordered list of table_index values.
    """
    lookup = {table.table_index: table for table in tables}

    lines: list[str] = []
    for display_idx, table_idx in enumerate(candidate_indices, start=1):
        table = lookup[table_idx]
        lines.append(f"{display_idx}. Section: {table.section or 'N/A'}")
        body_lines = table.md_table_body.splitlines()[:2]
        header = body_lines[0] if body_lines else ""
        sample = body_lines[1] if len(body_lines) > 1 else ""
        lines.append(f"   First row: {header}")
        lines.append(f"   Second row: {sample}")

    prompt = (
        f"Question: {question}\n\n"
        "Which of the following document sections most likely answers this question? "
        "Reply with only the section number (1-based index).\n\n"
        + "\n".join(lines)
    )

    response = client.chat.completions.create(
        model=os.getenv("AZURE_OPENAI_DEPLOYMENT_NAME"),
        messages=[
            {
                "role": "system",
                "content": (
                    "You are a careful retrieval assistant. "
                    "Choose the single best document section index from the list."
                ),
            },
            {
                "role": "user",
                "content": prompt,
            },
        ],
        temperature=0,
        max_tokens=10,
    )
    content = (response.choices[0].message.content or "").strip()
    try:
        choice = int(content.split()[0]) - 1  # 1-based → 0-based list index
        if 0 <= choice < len(candidate_indices):
            chosen_table_idx = candidate_indices[choice]
            return [chosen_table_idx] + [idx for idx in candidate_indices if idx != chosen_table_idx]
    except ValueError:
        pass
    return candidate_indices


def find_relevant_tables(question: str, tables: list[AnnotatedTable], full_markdown: str) -> list[AnnotatedTable]:
    """
    Return tables relevant to the question, ranked using semantic similarity
    and an optional LLM re-ranking step.
    """
    candidate_indices = _select_candidate_indices(question, tables)
    if not candidate_indices:
        return []

    if len(candidate_indices) > 1:
        candidate_indices = _rerank_with_llm(question, tables, candidate_indices)

    lookup = {table.table_index: table for table in tables}
    return [lookup[idx] for idx in candidate_indices if idx in lookup]


# ── Main QA logic ─────────────────────────────────────────────────────────────

def answer(question: str) -> QAAnswer:
    """
    Answer a question about the HSBC document using annotated markdown.

    Strategy:
      1. Load annotated markdown + parse VERIFY tags
      2. Find tables relevant to the question
      3. Check each table's VERIFY label:
         - CORRECT / REVIEW → answer directly from the annotated table content
         - INCORRECT / UNKNOWN → return page images from PDF_REF page numbers
      4. If no relevant table found → answer directly from full annotated markdown

    Returns QAAnswer with:
        status  : "answered" | "flagged" | "partial"
        answer  : str (LLM answer or refusal)
        images  : list of page image paths
        warning : str | None
    """
    # ── 1. Load annotated markdown ─────────────────────────────────────────
    full_markdown, annotated_tables = load_annotated_markdown()

    if not full_markdown.strip():
        return QAAnswer(
            status="flagged",
            answer="No annotated document found. Please run the verifier first.",
            images=[],
            warning="⚠️ No annotated markdown available. Run: python verifier.py",
        )

    # ── 2. Find relevant tables ────────────────────────────────────────────
    relevant = find_relevant_tables(question, annotated_tables, full_markdown)

    if relevant:
        # Separate verified tables from unverified ones; prioritize verified.
        verified   = [t for t in relevant if t.label in ("CORRECT", "REVIEW")]
        unverified = [t for t in relevant if t.label not in ("CORRECT", "REVIEW")]
        table = verified[0] if verified else (unverified[0] if unverified else None)

        if not table:
            return QAAnswer(
                status="flagged",
                answer="Unable to resolve a relevant table for this question.",
                images=[],
                warning="⚠️ No suitable table could be selected for this question.",
            )

        # ── 3a. CORRECT / REVIEW → answer directly ─────────────────────
        if table.label in ("CORRECT", "REVIEW"):
            # Detect when a verified table was chosen over a semantically
            # superior but INCORRECT table — warn the user to check images too.
            best_unverified_score = 0.0
            best_unverified_table: AnnotatedTable | None = None
            if unverified:
                question_emb = embed(question)
                for t in unverified:
                    cached = _embedding_cache.get(t.table_index)
                    if cached is not None:
                        s = cosine_similarity(question_emb, cached)
                        if s > best_unverified_score:
                            best_unverified_score = s
                            best_unverified_table = t

                # Warn when the unverified best-match is meaningfully better.
                best_verified_score = 0.0
                for t in verified:
                    cached = _embedding_cache.get(t.table_index)
                    if cached is not None:
                        s = cosine_similarity(question_emb, cached)
                        if s > best_verified_score:
                            best_verified_score = s

            semantic_gap_warning: str | None = None
            if best_unverified_table and (best_unverified_score - best_verified_score) > 0.05:
                reason_str = ", ".join(best_unverified_table.error_reasons) if best_unverified_table.error_reasons else "verification_failed"
                semantic_gap_warning = (
                    f"⚠️  Note: a semantically more relevant table (confidence={best_unverified_table.confidence:.2f}, "
                    f"reason: {reason_str}) was marked INCORRECT. "
                    f"The answer below comes from a less-semantically-relevant but verified table. "
                    f"Please cross-check with the original page image(s)."
                )

            llm_answer = answerdirectly(question, table.md_table_body)

            # When skipping an INCORRECT table, also return its page image
            images: list[Path] = []
            if best_unverified_table and (best_unverified_score - best_verified_score) > 0.05:
                if best_unverified_table.pdf_page:
                    images = find_page_images([best_unverified_table.pdf_page])

            return QAAnswer(
                status="answered",
                answer=llm_answer,
                images=images,
                warning=semantic_gap_warning,
                table_verdict=table,
            )

        # ── 3b. INCORRECT / UNKNOWN → return page images ───────────────
        page_images: list[Path] = []
        if table.pdf_page:
            page_images = find_page_images([table.pdf_page])

        reason_str = ", ".join(table.error_reasons) if table.error_reasons else "verification_failed"
        warning = (
            f"⚠️  The relevant table was verified as INCORRECT (confidence={table.confidence:.2f}). "
            f"Reason: {reason_str}. "
            f"The answer cannot be provided from the markdown as it may contain errors. "
            f"Please consult the original page image(s) below."
        )

        return QAAnswer(
            status="flagged",
            answer=(
                f"I cannot provide a reliable answer for this question because the relevant "
                f"section was verified as INCORRECT (reason: {reason_str}, confidence={table.confidence:.2f}). "
                f"Please refer to the original page image(s) for the accurate information."
            ),
            images=page_images,
            warning=warning,
            table_verdict=table,
        )

    # ── 4. No relevant table found → token-safe fallback ─────────────────────
    # Take top-3 tables by raw embedding score and build a limited context.
    _ensure_table_embeddings(annotated_tables)
    question_embedding = embed(question)

    ranked = []
    for table in annotated_tables:
        cached = _embedding_cache.get(table.table_index)
        if cached is not None:
            score = cosine_similarity(question_embedding, cached)
            ranked.append((score, table))

    ranked.sort(key=lambda item: item[0], reverse=True)
    top3 = [tbl for _, tbl in ranked[:3]]

    # Build fallback context capped at ~6000 tokens (1 token ≈ 4 chars → 24000 chars)
    fallback_parts: list[str] = []
    total_chars = 0
    char_limit = 24000
    for table in top3:
        part = table.md_table_body
        if total_chars + len(part) + 1 <= char_limit:
            fallback_parts.append(part)
            total_chars += len(part) + 1
        else:
            remaining = char_limit - total_chars
            if remaining > 0:
                fallback_parts.append(part[:remaining])
            break

    fallback_context = "\n\n".join(fallback_parts)
    llm_answer = answerdirectly(question, fallback_context)

    return QAAnswer(
        status="answered",
        answer=llm_answer,
        images=[],
        warning="Answer based on best-effort semantic match; no high-confidence table found.",
    )


# ── CLI helper ────────────────────────────────────────────────────────────────

def _print_result(result: QAAnswer) -> None:
    """Pretty-print a QAAnswer result to stdout."""
    print()
    if result.warning:
        print(result.warning)
        print()
    print("Answer:", result.answer)
    if result.images:
        print()
        print("Relevant page image(s) (verified INCORRECT — consult for accuracy):")
        for img in result.images:
            print(f"  {img}")
        print()
    if result.table_verdict:
        print(f"[Table {result.table_verdict.table_index + 1}] "
              f"Label: {result.table_verdict.label} | "
              f"Confidence: {result.table_verdict.confidence:.2f} | "
              f"Page: {result.table_verdict.pdf_page or 'N/A'}")
    print()


# ── Entry point ────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    q = input("Ask a question about the HSBC document: ")
    result = answer(q)
    _print_result(result)
